import Head from 'next/head'
import Image from 'next/image'
import { Heart } from 'framework7-icons/react'
import F7Icon from 'react-f7-icons'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {/* <F7Icon name="ant" fill="red" /> */}
        <Heart fill="red" width="2em" height="2em" />
        <F7Icon name="heart" fill="blue" />
      </div>
    </div>
  )
}
